urls:
  - https://news.google.com/?hl=ru
  - https://news.yandex.ru/

themes:
  - На несогласованной акции
  - жару
  - Японии
  - Полиция
  - Путин
  - акции
  - Подмосковье
  - губернатор
  - Bitcoin
  - крушения
  - задержали