urls:
  - https://news.google.com/?hl=ru
  - https://news.yandex.ru/
  - https://meduza.io/
  - https://rbc.ru/
  - https://vc.ru/
  - https://news.yandex.ru/
  - https://tjournal.ru/

themes:
  - вирус
  - COVID
  - вакцинация
  - Москв
  - Навальн
  - несогласован
  - жару
  - Японии
  - Полиция
  - Путин
  - президент
  - оппозиция
  - акции
  - Подмосковь
  - губернатор
  - Bitcoin
  - биткоин
  - криптовалют
  - блокчейн
  - технология
  - открыли
  - крушения
  - задержали