urls:
#  - https://news.google.com/?hl=ru
#  - https://news.yandex.ru/
#  - https://meduza.io/
#  - https://rbc.ru/
#  - https://vc.ru/
#  - https://news.yandex.ru/
#  - https://tjournal.ru/
   - link: https://tengrinews.kz/kazakhstan_news/
     selectors:
        - "body > div.my-app > main > section > div.tn-article-grid" # selectors
   - link: https://informburo.kz/
     selectors:
       - "#feed-switcher" # selectors
   - link: https://kapital.kz/
     selectors:
       - "#main-container > main > aside.main__aside-left > div > div.news-feed > article" # selectors
     excludeSelectors:
      - "information-article__category"

themes:
#  - вирус
#  - COVID
#  - вакцинация
#  - Москв
#  - Навальн
#  - несогласован
#  - жару
#  - Японии
#  - Полиция
#  - Путин
#  - президент
#  - оппозиция
#  - акции
#  - Подмосковь
#  - губернатор
#  - Bitcoin
#  - биткоин
#  - криптовалют
#  - блокчейн
#  - технология
#  - открыли
#  - крушения
#  - задержали